### ISSUE TITLE
USER STORY: Access social media pages

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#1]
As a **Site User** I can **access the golf club's social media page** so that **I can research the club further**

**Acceptance Criteria:**
- Acceptance Criteria 1: Include Links to all social media sites.
- Acceptance Criteria 2: Must be available to user at all times.
- Acceptance Criteria 3: Social sites to be represented by icons.

**Tasks**
- [x] Import social media icons for (Facebook, Twitter, Instagram and Youtube)
- [x] Within footer, create a div and equally divide four icons horizontally within anchor tags linked to social media sites.
- [x] Set background-color to match main theme
