### ISSUE TITLE
USER STORY: Cancel Tee Time

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#11]
As a **Site User** I can **cancel my tee time** so that **I have the ability to cancel my tee time at any time**

**Acceptance Criteria:**
- Acceptance Criteria 1: Each booking displayed within view_bookings.html to include a delete button
- Acceptance Criteria 2: Delete button to render delete_booking.html which ensures that user is certain they wish to delete booking.
- Acceptance Criteria 3: To include user feedback message if booking is deleted successfully.

**Tasks**
- [x] Create a Delete Button within each listed booking.
- [x] Create delete_booking.html with a 'Yes' button to delete and 'Cancel' to render view_bookings.html instead.
- [x] Create delete_booking function in views.py which gets specific booking using booking id and deletes specified booking.
- [x] Link delete_booking function with 'Yes' button in delete_booking.html to delete booking if clicked.
- [x] User message to display 'Your booking has been successfully deleted' once booking is deleted.
- [x] User to be re-rendered to updated view_bookings.html
