### ISSUE TITLE
USER STORY: View and Edit Bookings

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#12]
As a **Site User** I can **view and edit my bookings** so that **I can change some details without needing to contact the golf shop**

**Acceptance Criteria:**
- Acceptance Criteria 1: Once user booking is confirmed by admin, display details within view_bookings.html.
- Acceptance Criteria 2: Include an update button to allow users to update their booking which will need to be approved again.
- Acceptance Criteria 3: Users can update all fields of their booking as they wish.

**Tasks**
- [x] Create a view_bookings.html page which displays user booking information once approved by admin.
- [x] Add booking_status field to booking model and set default to False.
- [x] Create view_bookings function in views.py to render profile information within view_bookings.html.
- [x] Once booking_status is set to True, display booking in UX Design manner to the user.
- [x] Include an 'Update' button to allow user to update their booking.
- [x] Create edit_booking function in views.py which is to render booking_form and instance of particular booking (using ID).
- [x] Once Submit Button is clicked within booking_form, set booking_status to False again.
