### ISSUE TITLE
USER STORY: Create Tee Booking

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#13]
As a **Site User** I can **create a booking** so that **I can request a tee time with ease and using my profile details**

**Acceptance Criteria:**
- Acceptance Criteria 1: Have an application which holds all user booking details. Each new booking must be linked with logged in user.
- Acceptance Criteria 2: Once logged in and account created, user can book a tee time without needing personal details
- Acceptance Criteria 3: Each new booking to include Number of Holes, number of players, if club or buggie hire required, date of game, time of date, textfield for additional requirements and time of creation.
- Acceptance Criteria 4: Provide user with feedback if booking has been successfully and is waiting for approval. 

**Tasks**
- [x] Create a 'user_booking' application 
- [x] Create a model with fields to include "Number of Holes, number of players, if club or buggie hire required, date of game, time of date, textfield for additional requirements and time of creation."
- [x] Create form.py file to include listed fields from model
- [x] Create a view_bookings.html page which includes a 'Create Booking' button if user profile exists.
- [x] Create an add_booking.html page which will render booking form from previous task.
- [x] Create an 'Add_booking" function within views.py to render booking_form and save once fully completed.
- [x] User can only view booking details once confirmed by admin.
