### ISSUE TITLE
USER STORY: Sign Out my Account

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#19]
As a **Site User** I can **sign out of my account** so that **I can log out after booking a tee time**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Django AllAuth to allow users to Sign Out when returning to the website.
- Acceptance Criteria 2: Have Sign Out link within the nav element of base.html.
- Acceptance Criteria 3: Site User is asked to make sure they wish to sign out.

**Tasks**
- [x] Create a Nav Element which is linked with the logout.html page.
- [x] Style logout.html to look similar to signup.html and login.html using HTML and CSS.
- [x] Create a defensive user question with "Yes" to confirm signing out and "No" to cancel signing out.
