### ISSUE TITLE
USER STORY: View Reviews

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#2]
As a **Site User** I can **view reviews from previous players** so that **I can decide if I like the golf course**

**Acceptance Criteria:**
- Acceptance Criteria 1: Include a reviews section within the landing page for users to see.
- Acceptance Criteria 2: Users can click on a specific review for more details

**Tasks**
- [x] Create a section within index.html where reviews will be displayed.
- [x] Create a 'Review' application.
- [x] Create a review model to include title, slug, content, excerpt and status (Draft or Published) - Draft as default.
- [x] In views.py, create a ReviewList class to display reviews within section of index.html.
- [x] Paginate reviews to display two per page.
- [x] Create a review_page.html which is to display review details and style it for enhanced visual display.
- [x] Create a 'ReviewInDetail' class within views.py to render all review details within review_page.html.
