### ISSUE TITLE
USER STORY: View HalfWay House Menu

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#20]
As a **Site User** I can **view the halfway house's menu** so that **I know what they have to offer me, as a golfer during my break**

**Acceptance Criteria:**
- Acceptance Criteria 1: Must be well presented as a table and with photos.
- Acceptance Criteria 2: To include all beverages and food offered to golfers.
- Acceptance Criteria 3: To include opening and closing time and prices also.

**Tasks**
- [ ] Within the halfway house div of features section, a drop-down div using bootstrap.
- [ ] When clicked on by user, div must display table and each row to contain item and its price.
- [ ] Final row to include opening and closing time of half way house.
