### ISSUE TITLE
USER STORY: Recover Log In Password using Email

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#21]
As a **site user** I can **recover my password** so that **I don't have to create a new account if I forget it**.

**Acceptance Criteria:**
- Acceptance Criteria 1: Sign Up form must include email field and set to required.
- Acceptance Criteria 2: All HTML files linked with this feature must match main theme of HighDunes Golf Club.

**Tasks**
- [ ] Set account email sign up to required in settings.py.
- [ ] Within account templates.signup.html, include allauth email field within sign up form.
- [ ] Within account templates update email_confirm.html using custom CSS style to match main theme.
- [ ] Within account templates update email.html using custom CSS style to match main theme.
- [ ] Within account templates update password_change.html using custom CSS style to match main theme.
- [ ] Within account templates, update verification.html using custom CSS style to match main theme.
- [ ] Within account templates, update verified_email_required.html using custom CSS style to match main theme.
- [ ] Within account templates, update password_reset_from_key.html using custom CSS style to match main theme.
