### ISSUE TITLE
USER STORY: Golf Pro Information

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#22]
As a **Site User** I can **find information regarding the golf Pro** so that **I know who he is and I can identify him when visiting the golf course**

**Acceptance Criteria:**
- Acceptance Criteria 1: Section of Golf Pro must include a personal photo and 'about me' information
- Acceptance Criteria 2: Must be above google maps but under golf course information.

**Tasks**
- [ ] Create a section under showcase images but above google maps.
- [ ] Create a div to include a rounded photo of golf pro.
- [ ] Below photo, include a biography paragraph.
- [ ] Under bio, include a table representing golf pro feature such as available lessons, meetings, contact details.
