### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#23]
As a **Site User** I can **view a video of the layout of the course** so that **I can visually see the layout of the course**

**Acceptance Criteria:**
- Acceptance Criteria 1: video must cover at least 50% of screen on larger and medium screen while full screen on smaller screens.
- Acceptance Criteria 2: Must be shorter than 5 mins to maintain website speed and prevent long wait to load video.

**Tasks**
- [ ] Create a section for imported Youtube video right above showcase images.
- [ ] Create a div within, set its size using Bootstrap (col.sm.12, col.md.6).
- [ ] Using 'iframe' html tag, set src to youtube video link and its title.
