### ISSUE TITLE
USER STORY: About Golf Course

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#24]
As a **Site User** I can **view an about section of the golf course** so that **I can read about golf course's history**

**Acceptance Criteria:**
- Acceptance Criteria 1: Include a brief paragraph about the golf course
- Acceptance Criteria 2: The rest of the section should be included within a dropdown section so it is not displayed unless requested by the user.

**Tasks**
- [ ] Under landing page image, create a section to include a centered div.
- [ ] Include a centered paragraph element which includes a brief history of the golf course.
- [ ] Include a short paragraph underneath 'Click to read more'  with an ID.
- [ ] Within static/JS/script.js, find this element using the ID and create an extended history within here which is displayed if the user clicks on 'Click to read more'.
- [ ] Create an if statement here which will hide this extended paragraph if clicked again.
