### ISSUE TITLE
USER STORY: Upload Photo When Leaving a Review

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#25]
As a **Site User** I can **upload a photo** so that **I can back my review with photos uploaded**

**Acceptance Criteria:**
- Acceptance Criteria 1: Only one photo must be allowed to be uploaded for each review.
- Acceptance Criteria 2: Photo must be stored in a cloudinary database such as Cloudinary.

**Tasks**
- [ ] Within the Review app .models.py, create an addition field within the Review model.
- [ ] The image field must use CloudinaryField with a default of 'placeholder'.
- [ ] Makemigrations and migrate the updated model. 
- [ ] Install Cloudinary within the CLI of development environment and include it within INSTALLED APPS in settings.py.
- [ ] In review_page.html, at the top, include an image HTML tag to include the uploaded image.
- [ ] Style its width to 100% and height to a maximum of 40VH. 
- [ ] Use Opacity to darken the image and make it absolute.
- [ ] Using relative positioning, create a div box to include review details such as Title, created time and by name of user.
