### ISSUE TITLE
USER STORY: Local Competitions

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#26]
As a **Site User** I can **view what competitions are coming up** so that **I can decide whether or not to join them**

**Acceptance Criteria:**
- Acceptance Criteria 1: Have a separate page where upcoming competitions are displayed.
- Acceptance Criteria 2: Include a link to the competition page within header.
- Acceptance Criteria 3: Competition details to include date, time, number of players, prize, list of names.
- Acceptance Criteria 4: To include at least one golf course image.

**Tasks**
- [ ] Add a new unordered list element to the nav bar and call it 'Competitions'.
- [ ] Create a new file competitions.html.
- [ ] Include the base.html and create a visually attractive page which will list upcoming competitions.
- [ ] Using bootstrap cards and CSS, design the layout of competition details within each card.
