### ISSUE TITLE
USER STORY: View an Image Gallery

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#27]
As a **Site User** I can **view images of HighDunes Golf Club** so that **I get a real feel in terms of what to expect when I arrive**

**Acceptance Criteria:**
- Acceptance Criteria 1: Image gallery must include a minimum of 8 but no more than 15 images.
- Acceptance Criteria 2: Images to include best scenic images, halfway house example orders, driving range.
- Acceptance Criteria 3: section should not be bigger than 50VH and images kept smaller to maintain good website loading speed.

**Tasks**
- [ ] Create a section within the landing page for gallery images.
- [ ] Create a div which is 30% width and 30vh and centered within the section. 
- [ ] Include a scroll arrow on the right to allow users to click for new photo of no more than 15 images.
- [ ] Using static/js/script.js, create a function which queries the div containing the images.
- [ ] The function must enlarge the div box and the images within if the user clicks on it.
- [ ] Include an exit button which resets image size when clicked.
