### ISSUE TITLE
USER STORY: View Information Regarding The Golf Course

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#3]
As a **Site User** I can **view some information regarding the golf course ** so that **I can decide whether or not it has features that suits me as a golfer**

**Acceptance Criteria:**
- Acceptance Criteria 1: index.html to include information regarding the golf course.
- Acceptance Criteria 2: must include photos, course features.

**Tasks**
- [x] Within index.html, create a section to include course features (clubhire, buggies available and halfway house).
- [x] Create a section with three divs. Each div to include a photo and information. (Driving Range, Twilight Golf, Course Layout)
- [x] Landing Page Image to cover almost 100VH and 100% width with darkend div to include text (Welcome message, easter rates, sign up button).
