### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#5]
As a **Site User** I can **register an account** so that **I can book a tee time without filling in personal details every time**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Django AllAuth to allow users to create an account with an authenticated password
- Acceptance Criteria 2: Include username and password fields (minimum)

**Tasks**
- [x] Download allauth account templates
- [x] Create a Nav Element which is linked with the signup.html page
- [x] Style and include username and password within the account form.
