### ISSUE TITLE
USER STORY: Sign in to my account

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/HighDunes#9]
As a **Site User** I can **sign in to my account** so that **I can access essential site features**

**Acceptance Criteria:**
- Acceptance Criteria 1: Use Django AllAuth to allow users to Sign In when returning to the website.
- Acceptance Criteria 2: Use Username and Password to sign in.

**Tasks**
- [x] Create a Nav Element which is linked with the login.html page.
- [x] Style login.html to look similar to signup.html using HTML and CSS.
- [x] Customise log in form only to include username and password.
